### ISSUE TITLE
apispec beta tag issue

### ISSUE THREAD

**Issue by jstevensfit** [ergo/pyramid_apispec#11]
It looks like most versions of pyramid_apispec are pulling the latest build of apispec which is (in this particular case) causing code to break even if bound to a specific version of pyramid_apispec. 

Specifically the replacement of spec.definition() to spec.components.schema()
and
spec.add_path() to spec.path().

In relation to the current documentation and APISpec object.

Could you bind to a specific stable version of apispec to correct the issue?

**Comment by ergo** [comment]
Hey @jstevensfit I understand your pain, that is why I've made recent 0.3 release. It depends on latest beta, last version was 0.34 and then they suddenly jumped to 1.0 beta releases and made bw. incompatible changes.

My latest release works with latest APISpec, best way would be to pin it in your requirements own to 1.0.0b5 for now. I'm really hoping the API there stabilizes soon - as I don't want to hardcode pre 1.0 versions for now.

**Comment by ergo** [comment]
Yw.

You can either pin 

    pyramid_apispec==0.2.1
    apispec==1.0.0b1

to keep old behavior or 

    pyramid_apispec==0.3.0
    apispec==1.0.0b5

Does that help?

**Comment by jstevensfit** [comment]
Yes it does, I'll use the latter.
