### ISSUE TITLE
Does this SwaggerUI supports swagger format 3.0.0?

### ISSUE THREAD

**Issue by PatriSampaio** [ergo/pyramid_apispec#18]
I have a situation where I need to user swagger format 3.0.0, can I still use this SwaggerUI integration? Because a valid file(compiles fine in the swagger editor) is not being compiled in my pyramid application SwaggerUI. I'm missing some configuration?

**Comment by ergo** [comment]
Hi are you using latest version of the package? The default swagger UI is 3.35.2 which was released on Oct 15, 2020. I think it should be supporting 3.x format just fine.

**Comment by PatriSampaio** [comment]
Thanks @ergo. I was using `pyramid_apispec="0.3.3"`. I updated to the latest version and now it is working fine!
