### ISSUE TITLE
Error when loading demo

### ISSUE THREAD

**Issue by stevepiercy** [ergo/pyramid_apispec#2]
For the demo app, in the lower right corner of the Swagger UI, there is a red icon labeled "Error". Clicking the icon opens a new browser tab with the URL and content:

https://online.swagger.io/validator/debug?url=http://0.0.0.0:6543/openapi.json

```json
{"schemaValidationMessages":[{"level":"error","message":"Can't read from file http://0.0.0.0:6543/openapi.json"}]}
```

**Comment by ergo** [comment]
I've updated the demo to suggest using 127.0.0.1 so I'm closing this.
