### ISSUE TITLE
Support routes with regular expression

### ISSUE THREAD

**Issue by drnextgis** [ergo/pyramid_apispec#7]
pyramid_apispec don't handle routes with regular expression. For example:

```
config.add_route('resource.item', '/api/resource/{id:\d+}')
```

Swagger UI produces the following curl:

```
curl -X DELETE "http://localhost:6544/api/resource/{id:\d+}" -H "accept: application/json"
```

**Comment by ergo** [comment]
Thanks, I'll look into this.

**Comment by ergo** [comment]
Can you try trunk version of the package, this should be now fixed.

**Comment by drnextgis** [comment]
It works! Thank you very much.
