### ISSUE TITLE
Internet access is required to use api explorer

### ISSUE THREAD

**Issue by drnextgis** [ergo/pyramid_apispec#8]
It would be great to have an opportunity to use local assets.

**Comment by ergo** [comment]
Yes, I have code for that somewhere, however it would require pyramid_apispec to ship swagger UI JS/CSS files and upgrade the package with new releases of that project.

**Comment by ergo** [comment]
I think the best way to move forward with this would be for you to copy the code for swagger UI serving and modify it to load the files from your own static directory.
